CUDA_VISIBLE_DEVICES=0 python run_meta_mmd_trans_combined.py
 --test_flag
 --id 10001
 --sigma0 55
 --lr 0.00005
 --no_meta_flag
 --n_samples 3900
 --target_senten_num 3000
 --val_num 50
 --sigma 30
 --max_length 100
 --trial_num 10
 --num_hidden_layers 1
 --target_datasets HC3
 --text_generated_model_name chatGPT
 --base_model_name roberta-base-openai-detector
 --skip_baselines
 --mask_flag
 --transformer_flag
 --meta_test_flag
 --epochs 100
 --two_sample_test
 --relative_test
 --print_details
 --relative_test_extra_n_samples -1
 --test_dataset DetectRL
 --test_text_n_sample_rounds 10
 --test_dataset_answer machine
 --relative_test_mode normal
 --relative_test_reference_mode random
 --test_text_n_sample_tokens 256
 --relative_test_alpha 0.05
 --test_dataset_answer_mix_ratio 0.5
 --output_test_text_file
 --raid_split train
 --test_dataset_attack none
 --faster